function [ params ] = elements( element )
% ELEMENTS
% Get the parameters for a specified element. Return a structure of
% the following form:
%
% params = struct(  'CromerMann', CromerMann,...    A structure containing
%                                                   the Cromer-Mann
%                                                   coefficients.
%                   'fprime', f1,...                Dispersion correction
%                                                   factor f' (real part)
%                   'f2prime', f2,...               Dispersion correction
%                                                   factor f'' (imaginary
%                                                   part)
%                   'A', A,...                      Atomic mass
%                   'mu', mu,...                    Mass absorption
%                                                   coefficient (u/p)
%                   'B', B);                        Debye-Waller factor
%                                                   Btotal (Angstroms^2)
%
% All parameters from X'Pert Epitaxy standard library, unless otherwise
% noted. Note that while f' and f'' are in fact dependent on incident
% angle, the dependence is weak and hence they are treated here as
% constants.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

switch(element)
    case('Al2')
        CromerMann = struct('a1', 6.4202,...
                            'a2', 1.9002,...
                            'a3', 1.5936,...
                            'a4', 1.9646,...
                            'b1', 3.0387,...
                            'b2', 0.7426,...
                            'b3', 31.547199,...
                            'b4', 85.0886,...
                            'c', 1.1151);
        params = struct('CromerMann', CromerMann,...
                        'fprime', 0.204,...
                        'f2prime', 0.246,...
                        'A', 26.98,...
                        'mu', 48.6,...
                        'B', 0.77);     % International Tables of X-Ray Crystallography, Vol III, Table 3.3.5.1B (p 237)
    case('Ga2')
        CromerMann = struct('a1', 15.2354,...
                            'a2', 6.7006,...
                            'a3', 4.3591,...
                            'a4', 2.9623,...
                            'b1', 3.0669,...
                            'b2', 0.2412,...
                            'b3', 10.7805,...
                            'b4', 61.413502,...
                            'c', 1.7189);
        params = struct('CromerMann', CromerMann,...
                        'fprime', -1.354,...
                        'f2prime', 0.777,...
                        'A', 69.72,...
                        'mu', 67.9,...
                        'B', 0.68);     % International Tables of X-Ray Crystallography, Vol III, Table 3.3.5.1C (p 238)
    case('In2')
        CromerMann = struct('a1', 19.1624,...
                            'a2', 18.5596,...
                            'a3', 4.2948,...
                            'a4', 2.0396,...
                            'b1', 0.5476,...
                            'b2', 6.3776,...
                            'b3', 25.8499,...
                            'b4', 92.809,...
                            'c', 4.9391);
        params = struct('CromerMann', CromerMann,...
                        'fprime', -0.126,...
                        'f2prime', 5.045,...
                        'A', 114.82,...
                        'mu', 243,...
                        'B', 1.58);     % International Tables of X-Ray Crystallography, Vol III, Table 3.3.5.1C (p 238)
    case('O3')
        CromerMann = struct('a1', 3.0485,...
                            'a2', 2.2868,...
                            'a3', 1.5463,...
                            'a4', 0.867,...
                            'b1', 13.2771,...
                            'b2', 5.7011,...
                            'b3', 0.3239,...
                            'b4', 32.9089,...
                            'c', 0.2508);
        params = struct('CromerMann', CromerMann,...
                        'fprime', 0.047,...
                        'f2prime', 0.032,...
                        'A', 15.999,...
                        'mu', 184,...
                        'B', 0.00);     % Unknown, assume zero.       
    case('N3')
        CromerMann = struct('a1', 12.2126,...
                            'a2', 3.1322,...
                            'a3', 2.0125,...
                            'a4', 1.1663,...
                            'b1', 0.0057,...
                            'b2', 9.8933,...
                            'b3', 28.9975,...
                            'b4', 0.5826,...
                            'c', -11.529);
        params = struct('CromerMann', CromerMann,...
                        'fprime', 0.029,...
                        'f2prime', 0.018,...
                        'A', 14.008,...
                        'mu', 7.52,...
                        'B', 0.00);     % Unknown, assume zero.
    case('P3')
        CromerMann = struct('a1', 6.4345,...
                            'a2', 4.1791,...
                            'a3', 1.78,...
                            'a4', 1.4908,...
                            'b1', 1.9067,...
                            'b2', 27.157,...
                            'b3', 0.526,...
                            'b4', 68.1645,...
                            'c', 1.1149);
        params = struct('CromerMann', CromerMann,...
                        'fprime', 0.283,...
                        'f2prime', 0.434,...
                        'A', 30.975,...
                        'mu', 74.1,...
                        'B', 0.00);     % Unknown, assume zero.
    case('As3')
        CromerMann = struct('a1', 16.6723,...
                            'a2', 6.0701,...
                            'a3', 3.4313,...
                            'a4', 4.2779,...
                            'b1', 2.6345,...
                            'b2', 0.2647,...
                            'b3', 12.9479,...
                            'b4', 47.7972,...
                            'c', 2.531);
        params = struct('CromerMann', CromerMann,...
                        'fprime', -1.011,...
                        'f2prime', 1.006,...
                        'A', 74.91,...
                        'mu', 83.4,...
                        'B', 0.43);     % International Tables of X-Ray Crystallography, Vol III, Table 3.3.5.1C (p 239)
    case('Sb3')
        CromerMann = struct('a1', 19.6418,...
                            'a2', 19.0455,...
                            'a3', 5.0371,...
                            'a4', 2.6827,...
                            'b1', 5.3034,...
                            'b2', 0.4607,...
                            'b3', 27.9074,...
                            'b4', 75.2825,...
                            'c', 4.5909);
        params = struct('CromerMann', CromerMann,...
                        'fprime', -0.287,...
                        'f2prime', 5.894,...
                        'A', 121.76,...
                        'mu', 270,...
                        'B', 0.58);     % International Tables of X-Ray Crystallography, Vol III, Table 3.3.5.1C (p 239)
    case('Bi3')
        CromerMann = struct('a1', 3.3689,...
                            'a2', 12.951,...
                            'a3', 16.5877,...
                            'a4', 6.4692,...
                            'b1', 0.704,...
                            'b2', 2.3928,...
                            'b3', 8.937,...
                            'b4', 48.0093,...
                            'c', 13.5782);
        params = struct('CromerMann', CromerMann,...
                        'fprime', -4.0111,...
                        'f2prime', 8.931,...
                        'A', 208.98,...
                        'mu', 240,...   % International Tables of X-Ray Crystallography, Vol III, Table 3.3.2A (page 162-163).
                        'B', 1.01);     % International Tables of X-Ray Crystallography, Vol III, Table 3.3.5.1C (p 239)
    case('Cd')
        CromerMann = struct('a1', 19.221,...
                            'a2', 17.644,...
                            'a3', 4.4610,...
                            'a4', 1.6029,...
                            'b1', 0.5946,...
                            'b2', 6.9089,...
                            'b3', 24.701,...
                            'b4', 87.482,...
                            'c', 5.0694);
        params = struct('CromerMann', CromerMann,...
                        'fprime', -0.079,...
                        'f2prime', 4.653,...
                        'A', 112.41,...
                        'mu', 231,...
                        'B', 0.00);     % Unknown, assume zero.
    case('Mg')
        CromerMann = struct('a1', 5.4204,...
                            'a2', 2.1735,...
                            'a3', 1.2269,...
                            'a4', 2.3073,...
                            'b1', 2.8275,...
                            'b2', 79.261,...
                            'b3', 0.3808,...
                            'b4', 7.1937,...
                            'c', 0.8584);
        params = struct('CromerMann', CromerMann,...
                        'fprime', 0,...     % Unknown, assume zero.
                        'f2prime', 0,...    % Unknown, assume zero.
                        'A', 24.305,...
                        'mu', 0,...         % Unknown, assume zero.
                        'B', 0.00);         % Unknown, assume zero.
    case('Te')
        CromerMann = struct('a1', 19.964,...
                            'a2', 19.014,...
                            'a3', 6.1449,...
                            'a4', 2.5239,...
                            'b1', 4.8174,...
                            'b2', 0.4209,...
                            'b3', 28.528,...
                            'b4', 70.840,...
                            'c', 4.352);
        params = struct('CromerMann', CromerMann,...
                        'fprime', -0.418,...
                        'f2prime', 6.352,...
                        'A', 127.6,...
                        'mu', 282,...
                        'B', 0.00);         % Unknown, assume zero.                    
    otherwise
%         error('ERRCODE011: Element not found!');

end

